import pandas as pd
from openai import OpenAI
import os

print("Loading threat telemetry ledger...")

# 1. Grab your Top 3 Critical Threats from your generated identity data ledger
try:
    risk_ledger = pd.read_csv("identity_risk_ledger.csv")
    critical_threats = risk_ledger[risk_ledger['risk_tier'] == 'CRITICAL'].head(3)
    threat_data_for_ai = critical_threats.to_string(index=False)
except FileNotFoundError:
    print("Error: Please run 'python analyse.py' first to create the ledger!")
    exit()

# 2. Grab your Puter token from the environment variables
puter_token = os.getenv("PUTER_AUTH_TOKEN")
if not puter_token:
    print("⚠️ WARNING: PUTER_AUTH_TOKEN environment variable not found.")
    print("Please set your token using: $env:PUTER_AUTH_TOKEN='your_token'")
    exit()

print("Initializing OpenAI client with Puter's universal cloud gateway...")
client = OpenAI(
    base_url="https://api.puter.com/puterai/openai/v1/",
    api_key=puter_token
)

prompt = f"""
You are a Principal Cloud Security Architect and CISO Advisor at CrowdStrike.
Analyze the following critical cross-platform identity sprawl risks found in our hybrid environment:

{threat_data_for_ai}

Generate an executive security incident summary report. For EACH of the identities listed:
1. State the exact blast radius risk (e.g., what could a malicious actor do with this?)
2. Provide a 3-step urgent remediation plan using platform-specific instructions (Active Directory, AWS IAM, Okta).
Make the tone sharp, professional, and authoritative.
"""

print("Routing query to Gemini via Puter... 🚀")
try:
    # 🎯 NOTE: Change model to Google's official identifier on Puter
    response = client.chat.completions.create(
        model="google/gemini-3.5-flash",  
        messages=[{"role": "user", "content": prompt}]
    )
    
    print("\n=======================================================")
    print("🛡️ CISO EXECUTIVE REMEDIATION REPORT (GENERATED BY AI) 🛡️")
    print("=======================================================\n")
    ai_report_text = response.choices[0].message.content
    print(ai_report_text)

    # Save the output for your upcoming judge demo
    with open("ai_executive_report.txt", "w", encoding="utf-8") as f:
        f.write(ai_report_text)
    print("\n[Saved report to disk as ai_executive_report.txt]")

except Exception as e:
    print(f"API Error occurred: {e}")