/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AttackPathRouteImport } from './routes/attack-path'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdentitiesIndexRouteImport } from './routes/identities.index'
import { Route as IdentitiesIdRouteImport } from './routes/identities.$id'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackPathRoute = AttackPathRouteImport.update({
  id: '/attack-path',
  path: '/attack-path',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesIndexRoute = IdentitiesIndexRouteImport.update({
  id: '/identities/',
  path: '/identities/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesIdRoute = IdentitiesIdRouteImport.update({
  id: '/identities/$id',
  path: '/identities/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attack-path': typeof AttackPathRoute
  '/compliance': typeof ComplianceRoute
  '/graph': typeof GraphRoute
  '/incidents': typeof IncidentsRoute
  '/reports': typeof ReportsRoute
  '/identities/$id': typeof IdentitiesIdRoute
  '/identities/': typeof IdentitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attack-path': typeof AttackPathRoute
  '/compliance': typeof ComplianceRoute
  '/graph': typeof GraphRoute
  '/incidents': typeof IncidentsRoute
  '/reports': typeof ReportsRoute
  '/identities/$id': typeof IdentitiesIdRoute
  '/identities': typeof IdentitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attack-path': typeof AttackPathRoute
  '/compliance': typeof ComplianceRoute
  '/graph': typeof GraphRoute
  '/incidents': typeof IncidentsRoute
  '/reports': typeof ReportsRoute
  '/identities/$id': typeof IdentitiesIdRoute
  '/identities/': typeof IdentitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/attack-path'
    | '/compliance'
    | '/graph'
    | '/incidents'
    | '/reports'
    | '/identities/$id'
    | '/identities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/attack-path'
    | '/compliance'
    | '/graph'
    | '/incidents'
    | '/reports'
    | '/identities/$id'
    | '/identities'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/attack-path'
    | '/compliance'
    | '/graph'
    | '/incidents'
    | '/reports'
    | '/identities/$id'
    | '/identities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AttackPathRoute: typeof AttackPathRoute
  ComplianceRoute: typeof ComplianceRoute
  GraphRoute: typeof GraphRoute
  IncidentsRoute: typeof IncidentsRoute
  ReportsRoute: typeof ReportsRoute
  IdentitiesIdRoute: typeof IdentitiesIdRoute
  IdentitiesIndexRoute: typeof IdentitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attack-path': {
      id: '/attack-path'
      path: '/attack-path'
      fullPath: '/attack-path'
      preLoaderRoute: typeof AttackPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities/': {
      id: '/identities/'
      path: '/identities'
      fullPath: '/identities/'
      preLoaderRoute: typeof IdentitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities/$id': {
      id: '/identities/$id'
      path: '/identities/$id'
      fullPath: '/identities/$id'
      preLoaderRoute: typeof IdentitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AttackPathRoute: AttackPathRoute,
  ComplianceRoute: ComplianceRoute,
  GraphRoute: GraphRoute,
  IncidentsRoute: IncidentsRoute,
  ReportsRoute: ReportsRoute,
  IdentitiesIdRoute: IdentitiesIdRoute,
  IdentitiesIndexRoute: IdentitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
