/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdentitiesIndexRouteImport } from './routes/identities.index'
import { Route as IdentitiesIdRouteImport } from './routes/identities.$id'

const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesIndexRoute = IdentitiesIndexRouteImport.update({
  id: '/identities/',
  path: '/identities/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesIdRoute = IdentitiesIdRouteImport.update({
  id: '/identities/$id',
  path: '/identities/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/identities/$id': typeof IdentitiesIdRoute
  '/identities/': typeof IdentitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/identities/$id': typeof IdentitiesIdRoute
  '/identities': typeof IdentitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/identities/$id': typeof IdentitiesIdRoute
  '/identities/': typeof IdentitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/incidents' | '/identities/$id' | '/identities/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/incidents' | '/identities/$id' | '/identities'
  id: '__root__' | '/' | '/incidents' | '/identities/$id' | '/identities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncidentsRoute: typeof IncidentsRoute
  IdentitiesIdRoute: typeof IdentitiesIdRoute
  IdentitiesIndexRoute: typeof IdentitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities/': {
      id: '/identities/'
      path: '/identities'
      fullPath: '/identities/'
      preLoaderRoute: typeof IdentitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities/$id': {
      id: '/identities/$id'
      path: '/identities/$id'
      fullPath: '/identities/$id'
      preLoaderRoute: typeof IdentitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentsRoute: IncidentsRoute,
  IdentitiesIdRoute: IdentitiesIdRoute,
  IdentitiesIndexRoute: IdentitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
